using LOD.Tools;

namespace LOD.Utils
{
    public class RoomDescriptions
    {
        public static string MountainTop = "A small courtyard atop of a mountain. There is an ancient temple in front of you and there are three paths down the mountain. One leads to a massive green forest, one leads to a rocky hot desert and one leads to a bleak icy tundra. You notice a stone in the corner of the courtyard with a message carved into it… ‘Dallen was here’. Where will you go?\n";
        public static string TempleDoor = "Dust and cobwebs cover everything, this place is very old. There is a massive stone door and ancient writing on the wall. What will you do?\n";
        public static string ForestEntrance = "You have entered a lush and peaceful forest... yet you can’t shake the feeling that you are being watched. You can see a tree village deeper in the forest. You also see a path leading back up the mountain.\n";
        public static string ForestEntranceShiaDefeated = "You have entered a lush and peaceful forest. The evil has been purged and the trees sigh in relief. You can see a tree village deeper in the forest. You also see a path leading back up the mountain.";
        public static string Desert = "You stand upon the sand dunes of the desert. The sun overhead is very hot and you are parched, you had better get moving soon. There is a pathway leading back up to the top of the mountain behind you. Ahead of you, in the distance you see a large wall encircling what seems like an abandoned village.\n";
        public static string ReadTheWall = "The wall reads: ‘Before time began and before spirits and life existed, the universe was in chaos. Then, three Golden Goddesses descended upon the chaos and began the creation of the world, each of them creating a different facet of the realm. Din created the material realm, Nayru gave the realm law and order, and Farore created all life forms that would follow the order. When their labors completed, the Goddesses departed for the heavens leaving behind three sacred stones, each representing a small portion of the essence of the goddesses.’ You notice a pedestal before the great stone door with three empty divots in it.\n";
        public static string OpenDoor = "The great stone door cracks open slowly to a heavenly bright light. You step over the threshold. You have escaped the strange world!\n";
        public static string ForestVillage= "A peaceful village of forest elves lives in the trees! Their elder approaches you: ‘Greetings traveler, welcome to our village. Magic stones you say? Yes I have one, I would be willing to give it to you if you can defeat the monster in the dark woods that has been terrorizing my people. I recommend Jiu-Jitsu training from our local dojo.\n";
        public static string ForestVillageShiaDefeated= "A peaceful village of forest elves lives in the trees! Their elder approaches you: ‘Thank you for saving our village, traveler! You are always welcome here.";
        public static string DarkWoods = "placeholder\n";
        public static string Dojo = "You enter the school. There are many students in white uniforms punching logs and throwing rocks. The sensei approaches you: ‘IF YOU CAN DODGE A ROCK, YOU CAN BODY SLAM A MONSTER!’ She hurls a rock into your stomach and you double over in pain. She is disappointed, and your training begins. You push yourself through an 80’s style training montage and become slightly more proficient in Jiu-Jitsu.\n";
        public static string DojoWithJiuJitsu = "You enter the school. There are many students in white uniforms punching logs and throwing rocks. The school leader approaches you: IF YOU CAN DODGE A ROCK, YOU CAN BODYSLAM A MONSTER! She hurls a rock at you but you barely get out of the way in time. ‘You have learned much, young grasshopper. You remind me of another student I once had. He possessed incredible power and terrible fury. I accidentally called him by the wrong name once and he went wild with rage!";
        public static string OpenMind = "You must look within yourself to save yourself from your other self. Only then will your true self reveal itself.\n";
        public static string VillageWall = $"A great stone wall looms over you. Through the village entrance, you can see what seems to be moving rocks scattered about the village. It may be a mirage? As you approach, an immense, iron-wrought gate crashes shut over the entrance with a CLANG. Atop the gate a man in chain mail armor and a well-groomed mustache appears. In an outrageous French accent, the man shouts down at you: ‘{TauntGenerator.Taunt()}’. The taunt cuts deep and you have no retort. The frustration is too much to bear and you feel that you must turn back to compose yourself.";
        public static string VillageWallWithOpenMind = "A great stone wall looms over you. Through the village entrance, you can see what seems to be moving rocks scattered about the village. It may be a mirage? As you approach, an immense, iron-wrought gate crashes shut over the entrance with a CLANG. Atop the gate a man in chain mail armor and a well-groomed mustache appears. The man begins to taunt you with an outrageous French accent but the enlightenment you received at the dojo tells you that he is merely projecting his own insecurities upon you. You remain composed and eventually the man gets bored and allows you to pass through.";
        public static string Taunt = TauntGenerator.Taunt();
        public static string DesertVillage = "You walk among dilapidated buildings and several boulders that are randomly strewn about. Suddenly they come alive! It is a society of stone golems! Their leader approaches you: 'Hey. You look tasty. Want play game? If win - you get shiny rock!' He shows you the traditional game of his people. It’s called 'Take the last rock to win.' The rules are pretty simple.";
        public static string RockGame = "";
        public static string RockGameLose = "The golem says 'I took last stone! Better luck next time, sucker!'";
        public static string RockGameWin = "The golem says 'You beat me! Take magic stone!' From the golem you receive a fiery ruby. It shines so brightly you are sure it could set even the deepest darkness alight!";
        public static string RockGameWinAgain = "The golem says 'You already shiny rock, but you still brilliant!'";
        public static string DesertVillageAsRockChampion = "You walk among dilapidated buildings and several boulders that are randomly strewn about. Suddenly they come alive! It is a society of stone golems! Their leader approaches you. He says to you: ‘only one other person has ever beat me at rock game… his name was… Dallen.";
        public static string IcyTundra = "Your eyes are blinded by a brewing blizzard. Everything is covered with ice and snow and you feel your body freezing over. A path to your right leads away into a dark and foreboding ravine. Straight ahead in the distance you see a castle with an ominous presence. On the path leading to that castle stands a stone with a carved inscription: ‘Only one with the stone of life and stone of fire can reach the chamber of the King and leave alive’";
        public static string Ravine = "At the end of the frightening ravine the path has led you to the base of a winding staircase carved into the cliff face. Any wind has stopped and the world holds its breath as up, up, up the stairs you go until you come to... a tunnel.";
        public static string ShelobsLair = "You enter the tunnel, wandering into darkness. Before you realize, your feet become tangled in thick webs. Echoing through the tunnel you hear a whisper, ‘Naughty little fly, why does it cry? Caught in a web! Soon you’ll be eaten.’ From every crack and crevice thousands of spiders emerge and swarm you! Nothing you do can shake the spiders from your body. Before you can think, you are overwhelmed as a voice cackles softly in the dark.";
        public static string ShelobsLairWithFaroresWind = "You enter the tunnel, wandering into darkness. Before you realize, your feet become tangled in thick webs. Echoing through the tunnel you hear a whisper, ‘Naughty little fly, why does it cry? Caught in a web! Soon you’ll be eaten.’ From every crack and crevice thousands of spiders emerge and swarm you! Just as the spiders begin to climb upon you, Farore’s Wind illuminates and a great gust of wind blasts through the tunnel sweeping up and blowing all spiders and disembodied voices out the tunnel and off the side of the mountain. You are left alone in the tunnel and notice for the first time some scribbling etched into the tunnel wall.";
        public static string ShelobsLairAfterSuccess = "The webs still decorate the tunnel thickly but you see no more spiders. Etched into the wall you notice again the inscription.";
        public static string ReadScribbles = "Upon looking closer at the wall, you see what appears to be a joke about a skeleton playing a brass instrument. You cannot read it fully because there are rough scratches through the words- as though someone had angrily tried to remove it. Beneath the inscription someone has signed the name 'King John'";
        public static string CastleEntrance = "As you enter the castle you notice that it is completely dark, you can't even see your hand in front of your face. It is bitterly cold and you hear water dripping off in the distance.";
        public static string CastleEntranceWithDinsFire = "As you enter the castle you notice that it is completely dark. Suddenly, Din's Fire glows brightly! The room is illuminated, you are in a very old courtyard. There is a rickety rope bridge that goes over a deep ravine to another room.";
        public static string SkeletonRoom = "You enter a room with a skeleton! It stands and stares at you blankly. It speaks: ‘Welcome to Castle Dallen my friend! If you are looking for an audience with the King, he broods in the throne room just beyond here’ you see a locked door behind the skeleton ‘Unfortunately, the King does not want to see anyone and has locked the door. I have a key- but I am very bored, I may be inclined to let you in if you can make me laugh.";
        public static string SkeletonRoomSuccess = "You enter a room with a skeleton! He doesn't seem to pay you any mind as he chuckles softly to himself and mutters something about skeleton keys.";
        public static string SkeletonJoke = "The Skeleton awaits eagerly. What joke do you tell him?";
        public static string JokeSuccess = "The skeleton cackles! ‘HAHAHAHA, too true, too true. I have a skeleton key right here in fact!’ The skeleton tosses you a bone-white key. ‘I’ll give you some advice for the great joke- the King is in a particularly bad mood today. Be careful not to call him by the wrong name, that's his biggest pet peeve!’";
        public static string JokeNoReaction = "The skeleton thinks for a moment putting a bony finger to his cracked temple. ‘Hmm, I don’t get it.’ he says. Your wit is unappreciated here";
        public static string JokeFail = "The skeleton jumps in anger! He shouts ‘How dare you! Everyone knows you cannot play the trombone without lungs! This is for all the bony musicians you have offended!’ The skeleton pulls a lever and the floor gives way beneath your feet. You fall to your death.";
        public static string ThroneRoom = "You approach King Dallen walking over a path paved with bones. He sits on a skull-adorned throne, and sips wine out of a matching skull goblet. ‘Greetings traveler!’ He says, ‘If you can guess my true name I may let you live! Otherwise I’d love to add your skull to my collection. What say you?’";
    }
}
