using LOD.Tools;

namespace LOD.Utils
{
    public class RoomDescriptions
    {
        public static string MountainTop = "A small courtyard atop of a mountain. There is an ancient temple in front of you and there are three paths down the mountain. One leads to a massive green forest, one leads to a rocky hot desert and one leads to a bleak icy tundra. You notice a stone in the corner of the courtyard with a message carved into it… ‘dallen was here’. Where will you go?\n";
        public static string TempleDoor = "Dust and cobwebs cover everything, this place is very old. There is a massive stone door and ancient writing on the wall. What will you do?\n";
        public static string ForestEntrance = "You have entered a lush and peaceful forest… yet you can’t shake the feeling that you are being watched. You can see a tree village deeper in the forest. You also see a path leading back up the mountain.\n";
        public static string ForestEntranceShiaDefeated = "You have entered a lush and peaceful forest. The evil has been purged and the trees sigh in relief. You can see a tree village deeper in the forest. You also see a path leading back up the mountain.";
        public static string Desert = "You stand upon the sand dunes of the desert. The sun overhead is very hot and you are parched, you had better get moving soon. There is a pathway leading back up to the top of the mountain behind you. Ahead of you, in the distance you see a large wall encircling what seems like an abandoned village.\n";
        public static string ReadTheWall = "The wall reads: ‘Before time began and before spirits and life existed, the universe was in chaos. Then, three Golden Goddesses descended upon the chaos and began the creation of the world, each of them creating a different facet of the realm. Din created the material realm, Nayru gave the realm law and order, and Farore created all life forms that would follow the order. When their labors completed, the Goddesses departed for the heavens leaving behind three sacred stones, each representing a small portion of the essence of the goddesses.’ You notice a pedestal before the great stone door with three empty divots in it.\n";
        public static string OpenDoor = "The great stone door cracks open slowly to a heavenly bright light. You step over the threshold. You have escaped the strange world!\n";
        public static string ForestVillage= "A peaceful village of forest elves lives in the trees! Their elder approaches you: ‘Greetings traveler, welcome to our village. Magic stones you say? Yes I have one, I would be willing to give it to you if you can defeat the monster in the dark woods that has been terrorizing my people. I recommend Jiu-Jitsu training from our local dojo.\n";
        public static string ForestVillageShiaDefeated= "A peaceful village of forest elves lives in the trees! Their elder approaches you: ‘Thank you for saving our village traveler! You are always welcome here.";
        public static string DarkWoods = "placeholder\n";
        public static string Dojo = "You enter the school. There are many students in white uniforms punching logs and throwing rocks. The sensei approaches you: ‘IF YOU CAN DODGE A ROCK, YOU CAN BODY SLAM A MONSTER!’ She hurls a rock into your stomach and you double over in pain. She is disappointed, and your training begins. You push yourself through an 80’s style training montage and become slightly more proficient in Jiu-Jitsu.\n";
        public static string DojoWithJiuJitsu = "You enter the school. There are many students in white uniforms punching logs and throwing rocks. The school leader approaches you: IF YOU CAN DODGE A ROCK, YOU CAN BODYSLAM A MONSTER! She hurls a rock at you but you barely get out of the way in time. ‘You have learned much, young grasshopper. You remind me of another student I once had. He possessed incredible power and terrible fury. I accidentally called him by the wrong name once and he went wild with rage!";
        public static string OpenMind = "You must look within yourself to save yourself from your other self. Only then will your true self reveal itself.\n";
        public static string VillageWall = $"A great stone wall looms over you. Through the village entrance, you can see what seems to be moving rocks scattered about the village. It may be a mirage? As you approach, an immense, iron-wrought gate crashes shut over the entrance with a CLANG. Atop the gate a man in chainmail armor and a well-groomed mustache appears. In an outrageous French accent, the man shouts down at you: ‘{TauntGenerator.Taunt()}’. The taunt cuts deep and you have no retort. The frustration is too much to bear and you feel that you must turn back to compose yourself.";
        public static string VillageWallWithOpenMind = "A great stone wall looms over you. Through the village entrance, you can see what seems to be moving rocks scattered about the village. It may be a mirage? As you approach, an immense, iron-wrought gate crashes shut over the entrance with a CLANG. Atop the gate a man in chainmail armor and a well-groomed mustache appears. The man begins to taunt you with an outrageous French accent but the enlightenment you received at the dojo tells you that he is merely projecting his own insecurities upon you. You remain composed and eventually the man gets bored and allows you to pass through.";
        public static string Taunt = TauntGenerator.Taunt();
        public static string DesertVillage = "You walk among dilapidated buildings and several boulders that are randomly strewn about. Suddenly they come alive! It is a society of stone golems! Their leader approaches you:‘Hey.You look tasty.Want play game ? If win - you get good!’ He shows you the traditional game of his people.It’s called ‘take the last rock to win.’ The rules are pretty simple.";
        public static string DesertVillageAsRockChampion = "You walk among dilapidated buildings and several boulders that are randomly strewn about. Suddenly they come alive! It is a society of stone golems! Their leader approaches you. He says to you: ‘only one other person has ever beat me at rock game… his name was… Dallen.";
        public static string IcyTundra = "Your eyes are blinded by a brewing blizzard. Everything is covered with ice and snow and you feel your body freezing over. In the distance you see a dark ominous castle. On the path ahead of you stands a stone with a carved inscription: ‘Only one with the stone of life and stone of fire can reach the chamber of the King’.";
        public static string CastleEntrance = "As you enter the castle you notice that it is completely dark, you can't even see your hand in front of your face. It is bitterly cold and you hear water dripping off in the distance.";
        public static string CastleEntranceWithDinsFire = "As you enter the castle you notice that it is completely dark. Suddenly, Din's Fire glows brightly! The room is illuminated, you are in a very old courtyard. There is a rickety rope bridge that goes over a deep ravine to another room.";
        public static string SkeletonRoom = "You enter a room with a skeleton! It stands and stares at you blankly. It speaks: ‘Welcome to Castle Dallen my friend! You will find our lord sitting on his throne further on.’ You look to the next room and see a young man with a crown on his head sitting on a tall pile of skulls. He looks deep in thought. ‘You could also go into that room over there. I wouldn't though.’ You look to the other doorway but can see nothing past the cobways that enshroud the entrance.";
        public static string SpiderRoom = "You walk into a room full of webs and spiders. You immediately get stuck and thrash around. A millions spiders swarm over you, paralyze you with their venom and drain your precious life juices. Bummer.";
        public static string SpiderRoomWithFaroresWind = "You walk into a room full of webs and spiders. Suddenly, Farore's Wind comes to life and a whirlwind fills the room! All of the webs and spiders are swept away, revealing a simple stone slab that you didn't see before. It simply reads 'john'. You feel like this is really important.";
        public static string ThroneRoom = "You approach King Dallen walking over a path paved with bones. He sits on a skull-adorned throne, and sips wine out of a matching skull goblet. ‘Greetings traveler!’ He says, ‘If you can guess my true name I may let you live! Otherwise I’d love to add your skull to my collection. What say you?’";
    }
}
